title: KIE Group - Knowledge is Everything
author: KIE Group
email: karreiro@gmail.com
description: >
  Open source projects for business systems automation and management.
baseurl: ''
url: 'http://www.kiegroup.org'
markdown: kramdown
